name: Build and Push Docker Image

# This workflow will run every time code is pushed to the "main" branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub (we'll use GitHub Packages for simplicity here)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/my-devops-app:latest .

    # Step 4: Push the Docker image to GitHub Packages
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/my-devops-app:latest